version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: blogposting
      MYSQL_USER: blogposting
      MYSQL_PASSWORD: blogposting
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

